/**
 * challenge-api-service-prod
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The RateQuotesRateQuotes model module.
* @module model/RateQuotesRateQuotes
* @version 1.0
*/
export default class RateQuotesRateQuotes {
    /**
    * Constructs a new <code>RateQuotesRateQuotes</code>.
    * @alias module:model/RateQuotesRateQuotes
    * @class
    * @param lenderName {String} The name of the lender
    * @param loanType {String} The type of loan
    * @param interestRate {Number} The interest rate of the loan
    * @param closingCosts {Number} The fees the lender with charge when the loan is closed
    * @param monthlyPayment {Number} the required monthly payment
    * @param apr {Number} the APR of the loan
    */

    constructor(lenderName, loanType, interestRate, closingCosts, monthlyPayment, apr) {
        
        
        this['lenderName'] = lenderName;
        this['loanType'] = loanType;
        this['interestRate'] = interestRate;
        this['closingCosts'] = closingCosts;
        this['monthlyPayment'] = monthlyPayment;
        this['apr'] = apr;
        
    }

    /**
    * Constructs a <code>RateQuotesRateQuotes</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/RateQuotesRateQuotes} obj Optional instance to populate.
    * @return {module:model/RateQuotesRateQuotes} The populated <code>RateQuotesRateQuotes</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RateQuotesRateQuotes();
                        
            
            if (data.hasOwnProperty('lenderName')) {
                obj['lenderName'] = ApiClient.convertToType(data['lenderName'], 'String');
            }
            if (data.hasOwnProperty('loanType')) {
                obj['loanType'] = ApiClient.convertToType(data['loanType'], 'String');
            }
            if (data.hasOwnProperty('interestRate')) {
                obj['interestRate'] = ApiClient.convertToType(data['interestRate'], 'Number');
            }
            if (data.hasOwnProperty('closingCosts')) {
                obj['closingCosts'] = ApiClient.convertToType(data['closingCosts'], 'Number');
            }
            if (data.hasOwnProperty('monthlyPayment')) {
                obj['monthlyPayment'] = ApiClient.convertToType(data['monthlyPayment'], 'Number');
            }
            if (data.hasOwnProperty('apr')) {
                obj['apr'] = ApiClient.convertToType(data['apr'], 'Number');
            }
        }
        return obj;
    }

    /**
    * The name of the lender
    * @member {String} lenderName
    */
    'lenderName' = undefined;
    /**
    * The type of loan
    * @member {String} loanType
    */
    'loanType' = undefined;
    /**
    * The interest rate of the loan
    * @member {Number} interestRate
    */
    'interestRate' = undefined;
    /**
    * The fees the lender with charge when the loan is closed
    * @member {Number} closingCosts
    */
    'closingCosts' = undefined;
    /**
    * the required monthly payment
    * @member {Number} monthlyPayment
    */
    'monthlyPayment' = undefined;
    /**
    * the APR of the loan
    * @member {Number} apr
    */
    'apr' = undefined;




}
