/**
 * challenge-api-service-prod
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import Error from '../model/Error';
import RateQuotes from '../model/RateQuotes';

/**
* Default service.
* @module api/DefaultApi
* @version 1.0
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Request rate quotes
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/RateQuotes} and HTTP response
     */
    quotesGetWithHttpInfo(loanSize, creditScore, propertyType, occupancy) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'loanSize': loanSize,
        'creditScore': creditScore,
        'propertyType': propertyType,
        'occupancy': occupancy
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OUAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = RateQuotes;

      return this.apiClient.callApi(
        '/quotes', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Request rate quotes
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/RateQuotes}
     */
    quotesGet(loanSize, creditScore, propertyType, occupancy) {
      return this.quotesGetWithHttpInfo(loanSize, creditScore, propertyType, occupancy)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }

}
