/**
 * challenge-api-service-prod
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ChallengeApiServiceProd);
  }
}(this, function(expect, ChallengeApiServiceProd) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ChallengeApiServiceProd.RateQuotesRateQuotes();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RateQuotesRateQuotes', function() {
    it('should create an instance of RateQuotesRateQuotes', function() {
      // uncomment below and update the code to test RateQuotesRateQuotes
      //var instane = new ChallengeApiServiceProd.RateQuotesRateQuotes();
      //expect(instance).to.be.a(ChallengeApiServiceProd.RateQuotesRateQuotes);
    });

    it('should have the property lenderName (base name: "lenderName")', function() {
      // uncomment below and update the code to test the property lenderName
      //var instane = new ChallengeApiServiceProd.RateQuotesRateQuotes();
      //expect(instance).to.be();
    });

    it('should have the property loanType (base name: "loanType")', function() {
      // uncomment below and update the code to test the property loanType
      //var instane = new ChallengeApiServiceProd.RateQuotesRateQuotes();
      //expect(instance).to.be();
    });

    it('should have the property interestRate (base name: "interestRate")', function() {
      // uncomment below and update the code to test the property interestRate
      //var instane = new ChallengeApiServiceProd.RateQuotesRateQuotes();
      //expect(instance).to.be();
    });

    it('should have the property closingCosts (base name: "closingCosts")', function() {
      // uncomment below and update the code to test the property closingCosts
      //var instane = new ChallengeApiServiceProd.RateQuotesRateQuotes();
      //expect(instance).to.be();
    });

    it('should have the property monthlyPayment (base name: "monthlyPayment")', function() {
      // uncomment below and update the code to test the property monthlyPayment
      //var instane = new ChallengeApiServiceProd.RateQuotesRateQuotes();
      //expect(instance).to.be();
    });

    it('should have the property apr (base name: "apr")', function() {
      // uncomment below and update the code to test the property apr
      //var instane = new ChallengeApiServiceProd.RateQuotesRateQuotes();
      //expect(instance).to.be();
    });

  });

}));
